config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
        get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_error_messages.html.slim
// partials in "shared" directory can be used across all views

// "object" variable is passed by both @user and @micropost forms
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains #{pluralize(object.errors.count, "error")}
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_micropost_form.html.slim
= simple_form_for @micropost, html: { multipart: true } do |f|
  // object will be passed to error_messages. Object can be either micropost or user
  = render 'shared/error_messages', object: f.object
  = f.input :content, label: false, placeholder: "Compose new micropost..."
  = f.button :submit, "Post", class: "btn btn-primary"
  span.picture
    = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'

app/views/shared/_stats.html.slim
//if the user is not defined, assing the current user. That is useful because the partial is accessed both by home, where the user is not defined, also by show, where user is defined
- @user ||= current_user
.stats
  = link_to following_user_path(@user) do
    strong id="following" class="stat"
      = @user.following.count
    |  following

  = link_to followers_user_path(@user) do
    strong id="followers" class="stat"
      = @user.followers.count
    |  followers

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 50), current_user
h1 = current_user.name
span = link_to "view my profile", current_user
span = pluralize(current_user.microposts.count, "micropost")