config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
        get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.slim
footer.footer
  small
    | The
    a href="http://www.railstutorial.org/"  Ruby on Rails Tutorial 
    | by
    a href="http://www.michaelhartl.com/"  Michael Hartl
  nav
    ul
      li = link_to "About",   about_path
      li = link_to "Contact", contact_path
      li
        a href="http://news.railstutorial.org/"  News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Michael Hartl App", root_path, id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li = link_to "Home",   root_path
        li = link_to "Help",   help_path
        // logged_in method defined in sessions_helper
        - if logged_in?
          li = link_to "Users", users_path
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown"
              | Account
              b.caret
            ul.dropdown-menu
              li = link_to "Profile", current_user
              li = link_to "Settings", edit_user_path(current_user)
              li.divider
              li = link_to "Log out", logout_path, method: "delete"
        - else
          li = link_to "Log in", login_path

app/views/layouts/_shim.html.slim
// if IE is  < v9 include javascript
/![if lt IE 9]
  | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"</script>

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{full_title(yield(:title))}
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

    = render 'layouts/shim'



  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        // assign specific class depending on message type, in order to be styled by bootstrap
        div class= " alert alert-#{message_type} " = message

      = yield

      = render 'layouts/footer'

      // add debugging info ONLY in the development environment
      = debug(params) if Rails.env.development?